#!/bin/sh

# this hook is run after `rcup` is executed
# to run `rcup` without hooks, use the `-K` option

touch "$HOME"/.psqlrc.local

if [ -e "$HOME"/.vim/autoload/plug.vim ]; then
  vim -E -s +PlugUpgrade +qa
else
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
vim -u "$HOME"/.vim/bundles.vim +PlugUpdate +PlugClean! +qa

if [ ! -e "$HOME"/.zplug/init.zsh ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi
zplug install

reset -Q
